// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGy6tHByX0QxXLcJLuMWazfWSgWbgUA4g',
    appId: '1:919740703819:web:e8290d29f815919d99d9ce',
    messagingSenderId: '919740703819',
    projectId: 'currensee-e5506',
    authDomain: 'currensee-e5506.firebaseapp.com',
    storageBucket: 'currensee-e5506.firebasestorage.app',
    measurementId: 'G-R0G332TDR6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbSIGoIARNtN5KCxBzZKJFxT0pDekfVXs',
    appId: '1:919740703819:android:61c33e0294b1dedc99d9ce',
    messagingSenderId: '919740703819',
    projectId: 'currensee-e5506',
    storageBucket: 'currensee-e5506.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBU59YmjM2atgjYqIQ5UhdnzqN_aBLgYHU',
    appId: '1:919740703819:ios:064be549a0b2e49f99d9ce',
    messagingSenderId: '919740703819',
    projectId: 'currensee-e5506',
    storageBucket: 'currensee-e5506.firebasestorage.app',
    iosBundleId: 'com.example.eproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBU59YmjM2atgjYqIQ5UhdnzqN_aBLgYHU',
    appId: '1:919740703819:ios:064be549a0b2e49f99d9ce',
    messagingSenderId: '919740703819',
    projectId: 'currensee-e5506',
    storageBucket: 'currensee-e5506.firebasestorage.app',
    iosBundleId: 'com.example.eproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGy6tHByX0QxXLcJLuMWazfWSgWbgUA4g',
    appId: '1:919740703819:web:bf247b0a2b81598099d9ce',
    messagingSenderId: '919740703819',
    projectId: 'currensee-e5506',
    authDomain: 'currensee-e5506.firebaseapp.com',
    storageBucket: 'currensee-e5506.firebasestorage.app',
    measurementId: 'G-WT81KZBV1B',
  );
}
